# Método de Gauss

In [4]:
import numpy as np

def gauss(a,b):
    n,_=np.shape(a)
    A=np.c_[a,b]
    for i in range(n-1):
        for j in range(i+1,n):
            # Si el termino ya es cero continua con la siguiente
            if (A[j,i]!=0 and A[i,i]!=0):
                # factor de reduccion
                f=A[j,i]/A[i,i]
                A[j,i+1:n+1]=A[j,i+1:n+1]-f*A[i,i+1:n+1]
    # aplica la sustitucion inversa
    x=np.zeros(n)
    for i in range(n-1,-1,-1):
        x[i]=(A[i,n]-np.dot(A[i,i+1:n],x[i+1:n]))/A[i,i]
        
    return x

def main():
    a=np.array([[55.8 , 20.4 , 17.1 , 18.5 , 19.2 ],\
               [7.8  , 52.1 , 12.3 , 13.9 , 18.5 ],\
               [16.4 , 11.5 , 46.1 , 11.5 , 21.3 ],\
               [11.7 , 9.2  , 14.1 , 47.0 , 10.4 ],\
               [8.3  , 6.8  , 10.4 , 9.1  , 30.6 ]])
    b=np.array([2500,2000,2500,2000,1000])
    n,c=np.shape(a)
    r=np.linalg.matrix_rank(a)
    ab=np.c_[a,b]
    ra=np.linalg.matrix_rank(ab)
    
    print('rango(A)={} rango(Ab)={} n={}'.format(r,ra,n))
    
    if (r==ra==n):
        print('solucion unica')
        x=gauss(a,b)
        #x=np.linalg.solve(a, b)
        print(x)
    
    if (r==ra<n):
        print('multiples soluciones')
    
    if (r<ra):
        print('sin solucion')
        
if __name__ == "__main__": main()

rango(A)=5 rango(Ab)=5 n=5
solucion unica
[17.65270678 19.67904691 35.15143662 22.69415361  4.82265608]


 # Método de Gauss Jordan

In [5]:
import numpy as np

def gaussJordan(a,b):
    n,_=np.shape(a)
    A=np.c_[a,b]
    for i in range(n):
        for j in range(n):
            # Si el termino ya es cero continua con la siguiente
            if (A[j,i]!=0 and A[i,i]!=0 and i!=j):
                # factor de reduccion
                f=A[j,i]/A[i,i]
                A[j,i+1:n+1]=A[j,i+1:n+1]-f*A[i,i+1:n+1]
    # aplica la sustitucion inversa
    x=np.zeros(n)
    for i in range(n):
        x[i]=A[i,n]/A[i,i]
        
    return x

def main():
    a=np.array([[0.07, 0.18, 0.15, 0.24 ],\
               [0.03, 0.25, 0.10, 0.65 ],\
               [0.55, 0.41, 0.55, 0.09 ],\
               [0.35, 0.16, 0.20, 0.02 ]])
    b=np.array([0.15*100, 0.25*100, 0.4*100, 0.2*100])
    n,c=np.shape(a)
    r=np.linalg.matrix_rank(a)
    ab=np.c_[a,b]
    ra=np.linalg.matrix_rank(ab)
    
    print('rango(A)={} rango(Ab)={} n={}'.format(r,ra,n))
    
    if (r==ra==n):
        print('solución única')
        x=gaussJordan(a,b)
        #x=np.linalg.solve(a, b)
        print(x)
    
    if (r==ra<n):
        print('múltiples soluciones')
    
    if (r<ra):
        print('sin solución')
        
if __name__ == "__main__": main()

rango(A)=4 rango(Ab)=4 n=4
solución única
[37.29281768 18.64640884 17.12707182 26.93370166]


# Descomposición LU

In [1]:
## Ejemplo: 

In [6]:
import numpy as np
import scipy as sp

def main():
    a=np.array([[0.07, 0.18, 0.15, 0.24 ],\
               [0.03, 0.25, 0.10, 0.65 ],\
               [0.55, 0.41, 0.55, 0.09 ],\
               [0.35, 0.16, 0.20, 0.02 ]])
    b=np.array([0.15*100, 0.25*100, 0.4*100, 0.2*100])
    n,c=np.shape(a)
    r=np.linalg.matrix_rank(a)
    ab=np.c_[a,b]
    ra=np.linalg.matrix_rank(ab)
    
    print('rango(A)={} rango(Ab)={} n={}'.format(r,ra,c))
    
    if (r==ra==c):
        print('solucion unica')
        lu, piv = sp.linalg.lu_factor(a)
        x = sp.linalg.lu_solve((lu, piv), b)
        print(lu)
        print(x)
    
    if (r==ra<c):
        print('multiples soluciones')
        
    if (r<ra):
        print('sin solucion')
        
if __name__ == "__main__": main()

rango(A)=4 rango(Ab)=4 n=4
solucion unica
[[ 0.55        0.41        0.55        0.09      ]
 [ 0.05454545  0.22763636  0.07        0.64509091]
 [ 0.63636364 -0.44329073 -0.11896965  0.2486901 ]
 [ 0.12727273  0.5615016  -0.34206109 -0.04860692]]
[37.29281768 18.64640884 17.12707182 26.93370166]
